name: Pull Request Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: self-hosted  # Используем твой локальный раннер на Mac
    steps:
      # 1. Скачиваем код из ветки PR
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Настраиваем uv (официальный экшн от Astral)
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true # Включаем кеширование для максимальной скорости

      # 3. Устанавливаем зависимости из pyproject.toml ПЛЮС группу test
      - name: Install dependencies
        run: |
          uv venv
          uv sync --group test

      # 4. Запускаем тестов с явным указанием группы
      - name: Run Pytest
        run: |
          uv run --group test pytest tests/